version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: magic-collector-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./storage:/var/www/storage
      - ./bootstrap/cache:/var/www/bootstrap/cache
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/database/database.sqlite
    networks:
      - magic-collector
    depends_on:
      - redis
    command: >
      sh -c "composer install &&
             npm install &&
             php artisan key:generate --force &&
             php artisan migrate --force &&
             php artisan serve --host=0.0.0.0 --port=8000"

  vite:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: magic-collector-vite
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - "5173:5173"
    networks:
      - magic-collector
    command: npm run dev -- --host=0.0.0.0

  redis:
    image: redis:7-alpine
    container_name: magic-collector-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - magic-collector

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: magic-collector-queue
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    environment:
      - APP_ENV=local
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/database/database.sqlite
    networks:
      - magic-collector
    depends_on:
      - app
      - redis
    command: php artisan queue:work --tries=3

networks:
  magic-collector:
    driver: bridge

volumes:
  magic-collector-storage:
  magic-collector-cache: